### ISSUE TITLE
SDL 1.2.4 fails to build on Mac OS X 10.5/x84_64

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL-1.2#523]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.14
**Reported for operating system, platform:** Mac OS X 10.5 (Intel), x86_64

# Comments on the original bug report:

On 2009-10-20 15:53:16 +0000, Max Horn wrote:

> Just got a bug report by a user of my Fink package for SDL reporting that SDL 1.2.14 does not build on on Mac OS X 10.5/x84_64.
> 
> Looking at it, it seems that in revision 4860 a change was made that was meant to fix building on 32bit (and which partially reverted a change made before to fix building on 64bit) seems to be the cause. Specifically, this one:
> 
>   <http://www.libsdl.org/cgi/viewvc.cgi/trunk/SDL/src/cpuinfo/SDL_cpuinfo.c?r1=4847&r2=4860>
> 
> 
> This is the build error:
> 
> /bin/sh ./libtool --mode=compile gcc-4.0 -g -O2 -I/sw64/include -I./include -D_GNU_SOURCE=1 -DTARGET_API_MAC_CARBON -DTARGET_API_MAC_OSX -fvisibility=hidden  -I/usr/X11R6/include -DXTHREADS -D_THREAD_SAFE -force_cpusubtype_ALL -fpascal-strings -c ./src/cpuinfo/SDL_cpuinfo.c -o build/SDL_cpuinfo.lo
> libtool: compile:  gcc-4.0 -g -O2 -I/sw64/include -I./include -D_GNU_SOURCE=1 -DTARGET_API_MAC_CARBON -DTARGET_API_MAC_OSX -fvisibility=hidden -I/usr/X11R6/include -DXTHREADS -D_THREAD_SAFE -force_cpusubtype_ALL -fpascal-strings -c ./src/cpuinfo/SDL_cpuinfo.c -fno-common -DPIC -o build/.libs/SDL_cpuinfo.o
> ./src/cpuinfo/SDL_cpuinfo.c: In function 'SDL_GetCPUFeatures':
> ./src/cpuinfo/SDL_cpuinfo.c:167: error: PIC register '%rbx' clobbered in 'asm'
> ./src/cpuinfo/SDL_cpuinfo.c:167: error: PIC register '%rbx' clobbered in 'asm'
> ./src/cpuinfo/SDL_cpuinfo.c:236: error: PIC register '%rbx' clobbered in 'asm'
> ./src/cpuinfo/SDL_cpuinfo.c:236: error: PIC register '%rbx' clobbered in 'asm'
> ./src/cpuinfo/SDL_cpuinfo.c:236: error: PIC register '%rbx' clobbered in 'asm'
> ./src/cpuinfo/SDL_cpuinfo.c:167: error: PIC register '%rbx' clobbered in 'asm'
> ./src/cpuinfo/SDL_cpuinfo.c:167: error: PIC register '%rbx' clobbered in 'asm'
> make: *** [build/SDL_cpuinfo.lo] Error 1
> ### execution of ./configure failed, exit code 2

On 2009-10-20 21:45:08 +0000, Sam Lantinga wrote:

> Interesting, it appears to work fine in GCC 4.2, perhaps it's a bug that's since been fixed?

On 2009-10-20 23:53:39 +0000, Max Horn wrote:

> Sam, I can confirm that it works with GCC 4.2. As such, I guess this can be considered "false alarm" resp. "bug in compiler".
> 
> Closing this, then :).

On 2009-10-21 07:34:05 +0000, Sam Lantinga wrote:

> Thanks!
