### ISSUE TITLE
Debian bug report: sdl-config --static-libs doesn't add Required.private libs

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL-1.2#737]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.15
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2013-07-27 14:26:48 +0000,  wrote:

> Original report:
> http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=698052
> --------------
> Compiling a program statically with `sdl-config --static-libs ...` will result 
> in missing symbols:
> 
> /usr/lib/i386-linux-gnu/libX11.a(ClDisplay.o): In function `XCloseDisplay':
> (.text+0xbd): undefined reference to `xcb_disconnect'
> /usr/lib/i386-linux-gnu/libX11.a(OpenDis.o): In function `OutOfMemory':
> (.text+0x456): undefined reference to `xcb_disconnect'
> [...]
> 
> A pkg-config based config (.pc) would use "Required.private: x11" to fix this. 
> Adding also `pkg-config --static --libs x11` is currently used by me as 
> workaround. But this is no real solution
> --------------
> 
> Indeed, I verified that in Debian systems, /usr/lib/x86_64-linux-gnu/pkgconfig/x11.pc contains the line "Requires.private: xcb >= 1.1.92", so when one wants to compile linking X11 statically, it pulls more library flags for the compiler, including XCB.
> 
> $ pkg-config --libs --static x11
> -lX11 -lpthread -lxcb -lXau -lXdmcp
> 
> 
> Cheers.

On 2013-07-28 14:27:36 +0000, Sam Lantinga wrote:

> Good point, although I'm not sure what the portable solution would be.
> 
> Would you like to submit a patch that works for you?

On 2013-07-28 17:01:06 +0000,  wrote:

> Sorry, we don't have any patch for this or a clear idea about how to solve it, that's why I didn't mention it in the report.

On 2015-08-25 09:38:21 +0000, Ryan C. Gordon wrote:

> 
> Hello, and sorry if you're getting several copies of this message by email, since we are closing many bugs at once here.
> 
> We have decided to mark all SDL 1.2-related bugs as RESOLVED ENDOFLIFE, as we don't intend to work on SDL 1.2 any further, but didn't want to mark a large quantity of bugs as RESOLVED WONTFIX, to clearly show what was left unattended to and make it easily searchable.
> 
> Our current focus is on SDL 2.0.
> 
> If you are still having problems with an ENDOFLIFE bug, your absolute best option is to move your program to SDL2, as it will likely fix the problem by default, and give you access to modern platforms and tons of super-cool new features.
> 
> Failing that, we _will_ accept small patches to fix these issues, and put them in revision control, although we do not intend to do any further official 1.2 releases.
> 
> Failing that, please feel free to contact me directly by email (icculus@icculus.org) and we'll try to find some way to help you out of your situation.
> 
> Thank you,
> --ryan.
