### ISSUE TITLE
SDL 1.2 SVN fails to build on OS X 10.5 in 64bit mode

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL-1.2#505]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.14
**Reported for operating system, platform:** Mac OS X 10.5 (Intel), PowerPC

# Comments on the original bug report:

On 2009-09-24 13:16:05 +0000, Max Horn wrote:

> Current SDL 1.2 SVN luckily builds on several systems now: 10.4 (PPC and 32bit intel), 10.5 (32 bit) and 10.6 (32 bit). However, it fails to build on 10.5 in 64 bit mode:
> 
> 
> /bin/sh ./libtool --mode=compile gcc-4.0 -g -O2 -I/sw64/include -I./include -D_GNU_SOURCE=1 -DTARGET_API_MAC_CARBON -DTARGET_API_MAC_OSX -fvisibility=hidden  -I/usr/X11R6/include -DXTHREADS -D_THREAD_SAFE -force_cpusubtype_ALL -fpascal-strings -c ./src/video/quartz/SDL_QuartzEvents.m  -o build/SDL_QuartzEvents.lo
> gcc-4.0 -g -O2 -I/sw64/include -I./include -D_GNU_SOURCE=1 -DTARGET_API_MAC_CARBON -DTARGET_API_MAC_OSX -fvisibility=hidden -I/usr/X11R6/include -DXTHREADS -D_THREAD_SAFE -force_cpusubtype_ALL -fpascal-strings -c ./src/video/quartz/SDL_QuartzEvents.m  -fno-common -DPIC -o build/.libs/SDL_QuartzEvents.o
> ./src/video/quartz/SDL_QuartzEvents.m: In function 'QZ_InitOSKeymap':
> ./src/video/quartz/SDL_QuartzEvents.m:203: warning: 'GetScriptManagerVariable' is deprecated (declared at /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Script.h:993)
> ./src/video/quartz/SDL_QuartzEvents.m: In function 'QZ_PumpEvents':
> ./src/video/quartz/SDL_QuartzEvents.m:736: error: 'UsrActivity' undeclared (first use in this function)
> ./src/video/quartz/SDL_QuartzEvents.m:736: error: (Each undeclared identifier is reported only once
> ./src/video/quartz/SDL_QuartzEvents.m:736: error: for each function it appears in.)
> make: *** [build/SDL_QuartzEvents.lo] Error 1
> ### execution of ./configure failed, exit code 2
> 
> 
>  This seems to be due to a bug in the OS X headers shipped with 10.5: See for example this message from carbon-dev: <http://lists.apple.com/archives/carbon-dev/2009/Aug/msg00146.html>
> 
> While this is a bug in the OS headers, I still think it would be important (and doable) to workaround this. I'll try to come up with a workaround (but feel free to beat me to this :).
> One way would be to directly include OSService/Power.h ; another would be to add
> 
> #if __LP64__  && OS X version is 10.5
>   #define UsrActivity 1
> #endif
> 
> inside SDL_QuartzEvents.m

On 2009-09-26 04:42:52 +0000, Sam Lantinga wrote:

> This is fixed in subversion, thanks!
