### ISSUE TITLE
does not build with kernelheaders 2.6.16.27 change in input.h

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL-1.2#224]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.11
**Reported for operating system, platform:** Linux, Other

# Comments on the original bug report:

On 2006-09-12 08:48:25 +0000, Manuel Oetiker wrote:

> /bin/sh ./libtool --mode=compile gcc -g -O2 -I/usr/pack/gfxlibs-2.4-mo/i686-debian-linux3.1/include -I./include -D_GNU_SOURCE=1   -I/usr/X11R6/include -DXTHREADS -D_REENTRANT -DHAVE_LINUX_VERSION_H -c ./src/joystick/linux/SDL_sysjoystick.c  -o build/SDL_sysjoystick.lo
>  gcc -g -O2 -I/usr/pack/gfxlibs-2.4-mo/i686-debian-linux3.1/include -I./include -D_GNU_SOURCE=1 -I/usr/X11R6/include -DXTHREADS -D_REENTRANT -DHAVE_LINUX_VERSION_H -c ./src/joystick/linux/SDL_sysjoystick.c  -fPIC -DPIC -o build/.libs/SDL_sysjoystick.o
> In file included from /usr/include/linux/joystick.h:33,
>                  from src/joystick/linux/SDL_sysjoystick.c:33:
> /usr/include/linux/input.h:801: error: syntax error before "kernel_ulong_t"
> /usr/include/linux/input.h:805: error: syntax error before "evbit"
> /usr/include/linux/input.h:805: error: `BITS_PER_LONG' undeclared here (not in a function)
> /usr/include/linux/input.h:806: error: syntax error before "keybit"
> /usr/include/linux/input.h:806: error: `BITS_PER_LONG' undeclared here (not in a function)
> /usr/include/linux/input.h:807: error: syntax error before "relbit"

On 2006-09-14 02:48:25 +0000, Ryan C. Gordon wrote:

> 
> This is a bug in the kernel headers (kernel_ulong_t is only typedef'd for kernel builds and not userspace apps using the headers), and appears to be fixed in 2.6.17.13 (and probably earlier...I just grabbed the latest kernel release to see).
> 
> I'm not really certain this is worth working around in SDL, so I'm resolving this as WONTFIX.
> 
> --ryan.
> 
>
