### ISSUE TITLE
Undefined references at link time.

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL-1.2#557]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 1.2
**Reported for operating system, platform:** All, x86

# Comments on the original bug report:

On 2010-03-26 09:47:07 +0000, Paul Mc Quade wrote:

> This bug relates to SDL_strlcpy, SDL_strlcat, SDL_GetError, SDL_SetModuleHandle and SDL_getenv function calls. This bug only appears to happen at linking and affects non microsoft compliers like gcc and Open Watcom compliers.
> 
> 
> 
> C:\msys\usr\lib\libSDLmain.a(SDL_win32_main.o)||In function `redirect_output':|
> SDL-1.2\.\src\main\win32\SDL_win32_main.c|219|undefined reference to `SDL_strlcpy'|
> \SDL-1.2\.\src\main\win32\SDL_win32_main.c|220|undefined reference to `SDL_strlcat'|
> \SDL-1.2\.\src\main\win32\SDL_win32_main.c|243|undefined reference to `SDL_strlcpy'|
> \SDL-1.2\.\src\main\win32\SDL_win32_main.c|244|undefined reference to `SDL_strlcat'|
> C:\msys\usr\lib\libSDLmain.a(SDL_win32_main.o)||In function `console_main':|
> \SDL-1.2\.\src\main\win32\SDL_win32_main.c|296|undefined reference to `SDL_strlcpy'|
> s\SDL-1.2\.\src\main\win32\SDL_win32_main.c|301|undefined reference to `SDL_GetError'|
> \SDL-1.2\.\src\main\win32\SDL_win32_main.c|312|undefined reference to `SDL_SetModuleHandle'|
> C:\msys\usr\lib\libSDLmain.a(SDL_win32_main.o)||In function `WinMain':|
> \SDL-1.2\.\src\main\win32\SDL_win32_main.c|354|undefined reference to `SDL_getenv'|
> \SDL-1.2\.\src\main\win32\SDL_win32_main.c|386|undefined reference to `SDL_strlcpy'|
> ||=== Build finished: 9 errors, 0 warnings ===|

On 2011-12-29 01:17:38 +0000, Sam Lantinga wrote:

> Are you still seeing this with the latest SDL 1.2 snapshot?
> http://www.libsdl.org/tmp/SDL-1.2.zip

On 2011-12-30 01:25:45 +0000, Ryan C. Gordon wrote:

> 
> Bumping priority on a few bugs that I would like examined more closely before 1.2.15 is finalized. This is not a promise that a bug will be fixed. We may close it with WONTFIX or WORKSFORME or something, but I just want to make sure attention is paid.
> 
> --ryan.

On 2015-08-25 09:38:23 +0000, Ryan C. Gordon wrote:

> 
> Hello, and sorry if you're getting several copies of this message by email, since we are closing many bugs at once here.
> 
> We have decided to mark all SDL 1.2-related bugs as RESOLVED ENDOFLIFE, as we don't intend to work on SDL 1.2 any further, but didn't want to mark a large quantity of bugs as RESOLVED WONTFIX, to clearly show what was left unattended to and make it easily searchable.
> 
> Our current focus is on SDL 2.0.
> 
> If you are still having problems with an ENDOFLIFE bug, your absolute best option is to move your program to SDL2, as it will likely fix the problem by default, and give you access to modern platforms and tons of super-cool new features.
> 
> Failing that, we _will_ accept small patches to fix these issues, and put them in revision control, although we do not intend to do any further official 1.2 releases.
> 
> Failing that, please feel free to contact me directly by email (icculus@icculus.org) and we'll try to find some way to help you out of your situation.
> 
> Thank you,
> --ryan.
