### ISSUE TITLE
No fullscreen if no reparenting wm

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL-1.2#597]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.14
**Reported for operating system, platform:** Linux, Other

# Comments on the original bug report:

On 2010-09-27 10:23:31 +0000, David Demelier wrote:

> Since the version 1.2.14 we can't use the fullscreen mode with SDL based application if the Window manager does not reparent.
> 
> This can be tested with teeworlds, wormux, zsnes with cwm, dwm, awesome.
> 
> It's a famous bug now, and developers says that the problematic wm needs to reparent, things that they don't want.

On 2011-04-12 20:13:11 +0000, Jen Spradlin wrote:

> Thank you for your bug report!
> 
> We're busy working on getting SDL 1.3 ready for a high quality release, and want to make sure as many things are fixed there as possible.
> Could you check to see if your bug is resolved by the latest SDL 1.3 snapshot?
> http://www.libsdl.org/tmp/SDL-1.3.zip
> 
> Thanks!

On 2011-04-13 14:14:54 +0000, David Demelier wrote:

> I can't compile it on FreeBSD 8.2 amd64. It fails when trying to compile the joystick code :
> 
> libtool: compile:  gcc -g -O3 -I./include -mmmx -msse -msse2 
> -fvisibility=hidden -I/usr/X11R6/include -DHAVE_USBHID_H -DUSBHID_NEW 
> -D_REENTRANT -D_THREAD_SAFE -MMD -MT build/SDL_sysjoystick.lo -c 
> src/joystick/bsd/SDL_sysjoystick.c  -fPIC -DPIC -o 
> build/.libs/SDL_sysjoystick.o
> src/joystick/bsd/SDL_sysjoystick.c: In function 'SDL_SYS_JoystickUpdate':
> src/joystick/bsd/SDL_sysjoystick.c:465: error: dereferencing pointer to 
> incomplete type
> src/joystick/bsd/SDL_sysjoystick.c:489: error: dereferencing pointer to 
> incomplete type
> src/joystick/bsd/SDL_sysjoystick.c:499: error: dereferencing pointer to 
> incomplete type
> src/joystick/bsd/SDL_sysjoystick.c:507: error: dereferencing pointer to 
> incomplete type
> src/joystick/bsd/SDL_sysjoystick.c: In function 'report_alloc':
> src/joystick/bsd/SDL_sysjoystick.c:588: error: dereferencing pointer to 
> incomplete type
> src/joystick/bsd/SDL_sysjoystick.c:588: error: dereferencing pointer to 
> incomplete type
> gmake: *** [build/SDL_sysjoystick.lo] Error 1
> 
> Cheers,

On 2011-04-18 23:31:51 +0000, David Demelier wrote:

> I commented out the joystick code to test a simple fullscreen program and it works!

On 2011-12-30 00:54:17 +0000, Ryan C. Gordon wrote:

> (In reply to comment # 3)
> > I commented out the joystick code to test a simple fullscreen program and it
> > works!
> 
> Great!
> 
> We fixed that FreeBSD joystick code recently, too.  :)
> 
> --ryan.
