### ISSUE TITLE
SDL 1.2.15: 16-color VGA isn't disabled on x86 machines without sys/io.h

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL-1.2#684]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 1.2.15
**Reported for operating system, platform:** Linux, x86

# Comments on the original bug report:

On 2012-04-10 09:27:34 +0000,  wrote:

> SDL 1.2.15's fbcon assumes that all x86 machines with VGA 16-color support compiled into the kernel will also have sys/io.h. On the musl libc (or without sys/io.h), that assumption fails and the compile process errors out:
> 
> /bin/bash ./libtool --mode=compile gcc -D_GNU_SOURCE  -I./include -D_GNU_SOURCE=1 -fvisibility=hidden -D_REENTRANT -DHAVE_LINUX_VERSION_H -Wall -c ./src/video/fbcon/SDL_fbvideo.c  -o build/SDL_fbvideo.lo
> libtool: compile:  gcc -D_GNU_SOURCE -I./include -D_GNU_SOURCE=1 -fvisibility=hidden -D_REENTRANT -DHAVE_LINUX_VERSION_H -Wall -c ./src/video/fbcon/SDL_fbvideo.c  -fPIC -DPIC -o build/.libs/SDL_fbvideo.o
> ./src/video/fbcon/SDL_fbvideo.c:55:40: fatal error: sys/io.h: No such file or directory
> compilation terminated.
> make: *** [build/SDL_fbvideo.lo] Error 1
> 
> Due to the relative obscurity of musl libc, I believe this should be kept a minor bug.

On 2015-08-25 09:38:22 +0000, Ryan C. Gordon wrote:

> 
> Hello, and sorry if you're getting several copies of this message by email, since we are closing many bugs at once here.
> 
> We have decided to mark all SDL 1.2-related bugs as RESOLVED ENDOFLIFE, as we don't intend to work on SDL 1.2 any further, but didn't want to mark a large quantity of bugs as RESOLVED WONTFIX, to clearly show what was left unattended to and make it easily searchable.
> 
> Our current focus is on SDL 2.0.
> 
> If you are still having problems with an ENDOFLIFE bug, your absolute best option is to move your program to SDL2, as it will likely fix the problem by default, and give you access to modern platforms and tons of super-cool new features.
> 
> Failing that, we _will_ accept small patches to fix these issues, and put them in revision control, although we do not intend to do any further official 1.2 releases.
> 
> Failing that, please feel free to contact me directly by email (icculus@icculus.org) and we'll try to find some way to help you out of your situation.
> 
> Thank you,
> --ryan.

**Comment by sezero** [comment]
Fixed by commit b124d3bc6942 which check sys/io.h before enabling VGA16_FBCON_SUPPORT
